# EV Charging Points in Singapore

The notebook builds an end-to-end data pipeline for Singapore's electric-vehicle charging-point data.

### Problem statement
Singapore government provides grants for prospective car buyers to purchase electric car. While this is a great incentive to buy electric car, there are some concerns among new car buyers if there are sufficient charging points to go around. EV adoption depends on having enough accessible charging points. 

Four coursemates have come together to extract, clean, restructure, and store the data to perform a basic analysis to find out more about the infrastructures in different parts of Singapore for prospective electric car buyers to know.

### Objectives
•	Retrieve the latest batch of EV charging-point records from LTA DataMall using Python.

•	Understand the API response and isolate the actual charging-location dataset.

•	Flatten nested arrays into one row per unique charging-point ID.

•	Explore and validate the dataset for structure, duplicates, missing values and numeric consistency.

•	Transform selected fields into analysis-ready formats.

•	Load the prepared data into PostgreSQL using SQLAlchemy.

•	Design a dimensional model that supports operator, charger, status and location analysis.



### Sections:
- Extraction
- Transformation
- Cleaning
- Load
- Analysis

Credits: Contains information from [EV Charging Points Batch](https://datamall.lta.gov.sg/content/datamall/en/dynamic-data.html#Electric%20Vehicle%20Charging%20Network) accessed on 19 Aug 2026 from Land Transport Datamall which is made available under the terms of the [Singapore Open Data Licence version 1.0](https://datamall.lta.gov.sg/content/datamall/en/term-of-use.html)


---

## [ PREPARING FOR WORKSPACE ]

#### Import Tools / Libraries

In [1]:
import requests
import json
import pandas as pd
import numpy as np

import sqlalchemy as db
from sqlalchemy_utils import create_database, database_exists
from sqlalchemy import text

print(f'SQLAlchemy version: {db.__version__}')
print(f'Pandas version: {pd.__version__}')

SQLAlchemy version: 2.0.43
Pandas version: 2.3.3

## [ EXTRACTION ]
#### URL Request

Link to download the dataset is acquired from LTA DataMall through API using the instructions provided in the [API User Guide & Documentation](https://datamall.lta.gov.sg/content/dam/datamall/datasets/LTA_DataMall_API_User_Guide.pdf). The download link expires after 15 minutes.

In [2]:
# Return all electric vehicle charging points in Singapore and their availabilities in a single file.
# https://datamall.lta.gov.sg/content/datamall/en/dynamic-data.html (Pg 2)
# EV Charging Points Batch

# LTA API endpoint
url = "https://datamall2.mytransport.sg/ltaodataservice/EVCBatch"

headers = {
    "AccountKey": "rdJlbgAGS0SowiuhrqZ2bg==", # API Account Key: Provided by LTA's DataMall. Uniquely assigned. Not to be shared.
    "accept": "application/json"
}

response = requests.get(url, headers=headers)

if response.status_code == 200:
    print("Request is successful.\n")
else:
    print("Request failed. Please check URL and try again.\n")
print(response.text)

Request is successful.

{"odata.metadata":"https://datamall2.mytransport.sg/ltaodataservice/$metadata#evcBatch","value":[{"Link":"https://dmprod-datasets.s3.ap-southeast-1.amazonaws.com/ev-batch/2026-08-18/EVBatch-20260818095007.json?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEIn%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDmFwLXNvdXRoZWFzdC0xIkYwRAIgKLMzMukYCLApqnudc66qQIf%2FHzXYOujonRFQSFDc40UCIFrnoLOY4zUBuwFK7LnhJxUCkKt5AI2Qk2TYIp%2Ff4fn%2FKsIFCFIQBBoMMzQwNjQ1MzgxMzA0IgyENRTH28imdj1AzD8qnwX8ipI%2FB1lgMtsXMREyGZlp8e5sDjw0VvsiOTMNCWEAi7ztCUOT6iUt2HzI3%2Bpp%2BPmRbA3gypf%2B0zwgFiKoP7bdWxVwMQZb6By485jU15CXzm%2BfPXkKZIWohip7hedCWj%2BdZ5NpEUjFVKmPbsAgb4b7j30i3IdVbN7Z08s88aVrRauf96kZkXSRXpoTvnXiD0vlZpHoYDJEYKPmgSxwaQg1DLcbLckdLqOzVjI6QbGSuNzLpiEvcN%2BVf7qchCysosZ7iAzx1kxILCSBDsIIK7cNCjM5RRVWlnZbUjIvOVBApJ%2FVMTE3jQTcM2bUhcYjtJGSjU5%2FoIkFxwP8dUQsBVrMadoZuF2ijvHSOAUW3Oquv%2FRa%2Bb0ttKWRBlV%2BdSBEPyvA0xOGARYftTdQF7Ql4hVIdAIjN9i0xW6R8l437f9u0eowz12JTzycUXMOUiajIXv0bh328fVx3wWhaVe73r1bvWT8j5FemLjItd4o0rMoOX6kiy3Fif6nQxxvfdUdgbZ4wKmPGC0ogyxT57iZAlWVI9SeBDwzgAllgS4W63rBESRvy2BU04aF5OXISgo3tUX8VK%2F9e7xhBDLGwAwq7Qsh0kYU7p%2BL7I1w6J05zJUupk0SqEOoY8bV0zCRQQRG1lYmfNnGAXTA4N3Ee7U0Z%2FYvYbBmbAazevxhMmrp%2F9FJeaX%2B4a%2BkkviRyl0V3zGNYXrJZyFkvz3vYjX48XH9%2BQ19EyW5zXJsXaghVAUlh7Rsp%2FIB8wopj62D6hw5b9ImkQBYpVPlMhibuGywL2VRa5ABLV%2FYRMj0ElPEevT8KwYaz5rfz1QXH6nTAHpJKb7G4L8cWRU3tOO%2FQRJ%2BLmzP2K7rhGc%2FYqLyb%2BNQ2tSE98v4hEqzQYp9oX243bxHjzZ45DCzzI7UBjqyAeIbCRh%2Bs50D%2B4U7uqOhGdfrZo8B9REyOs0%2FBv99UxAk3YPOsJ%2F2d0fd72ZWTvdekQl2O98wFS9tuTslW%2B7ZPhhVs8RUgwsvnb%2F43zZWNifnTL%2BkGyVKjnuaeVxzb9H%2FMe3yD4pbb056qzMmol84ANUE%2Bot36NZDknAhkMFsbIyGomIZHOMfMlaWJksL4ZScnP%2BwxSD2g6XzVpR8lojaPrUwOGor7TvxfwPHurCdqjPuXIs%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260818T015315Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIAU6UAMAS4HQ5LIE6O%2F20260818%2Fap-southeast-1%2Fs3%2Faws4_request&X-Amz-Signature=bee92be91e70dc1a0a92bbc3b9cc0d5c3ded1c3e80a4893b44cb3c346e688ad1"}]}

#### Extract data from temporary download link & download

In [3]:
data = response.json() # Take the JSON data that came back from the API and turn it into Python dictionary
download_url = data["value"][0]["Link"]
print("Download link obtained successfully!")

file_response = requests.get(download_url)
print("File download status:", file_response.status_code)

Download link obtained successfully!
File download status: 200

### Inspect Data structure

In [4]:
ev_data = file_response.json() # Take the JSON data that came back from the API and turn it into Python dictionary
print(
    f'Type of data:\n{type(ev_data)}\n\n'  
    f'Top-level keys:\n {list(ev_data.keys())}\n\n'
    f'Preview:\n{file_response.text[:1000]}\n\n'
)

Type of data:
<class 'dict'>

Top-level keys:
 ['LastUpdatedTime', 'evLocationsData']

Preview:
{"LastUpdatedTime":"2026-08-18 09:50:00","evLocationsData":[{"address":"3E RIVER VALLEY ROAD SINGAPORE 179024","name":"CLARKE QUAY","longtitude":103.846728,"latitude":1.290314,"postalCode":"179024","chargingPoints":[{"status":"1","operatingHours":"","operator":"SP MOBILITY PTE. LTD.","position":"L4 50","name":"CLARKE QUAY","plugTypes":[{"plugType":"Type 2","price":"0.8066","current":"AC","powerRating":"22","priceType":"kWh","evIds":[{"evCpId":"R114861R-001","status":"1"}]}]},{"status":"1","operatingHours":"","operator":"SP MOBILITY PTE. LTD.","position":"L4 49","name":"CLARKE QUAY","plugTypes":[{"plugType":"Type 2","price":"0.8066","current":"AC","powerRating":"22","priceType":"kWh","evIds":[{"evCpId":"R114859D-001","status":"1"}]}]},{"status":"1","operatingHours":"","operator":"SP MOBILITY PTE. LTD.","position":"L4 51 \u0026 52","name":"CLARKE QUAY","plugTypes":[{"plugType":"Combo 2","price":"0.8938","current":"DC","powerRating":"50","priceType":"kWh","evIds":[{"evCpId":"R114858R-001"

In [5]:
print(f'No. of records: {len(ev_data['evLocationsData'])}')

No. of records: 2731

In [6]:
print(f'First record:\n\n {json.dumps(ev_data['evLocationsData'][0], indent=2)}') #format into readable text to understand structure

First record:

 {
  "address": "3E RIVER VALLEY ROAD SINGAPORE 179024",
  "name": "CLARKE QUAY",
  "longtitude": 103.846728,
  "latitude": 1.290314,
  "postalCode": "179024",
  "chargingPoints": [
    {
      "status": "1",
      "operatingHours": "",
      "operator": "SP MOBILITY PTE. LTD.",
      "position": "L4 50",
      "name": "CLARKE QUAY",
      "plugTypes": [
        {
          "plugType": "Type 2",
          "price": "0.8066",
          "current": "AC",
          "powerRating": "22",
          "priceType": "kWh",
          "evIds": [
            {
              "evCpId": "R114861R-001",
              "status": "1"
            }
          ]
        }
      ]
    },
    {
      "status": "1",
      "operatingHours": "",
      "operator": "SP MOBILITY PTE. LTD.",
      "position": "L4 49",
      "name": "CLARKE QUAY",
      "plugTypes": [
        {
          "plugType": "Type 2",
          "price": "0.8066",
          "current": "AC",
          "powerRating": "22",
          "priceType": "kWh",
          "evIds": [
            {
              "evCpId": "R114859D-001",
              "status": "1"
            }
          ]
        }
      ]
    },
    {
      "status": "1",
      "operatingHours": "",
      "operator": "SP MOBILITY PTE. LTD.",
      "position": "L4 51 & 52",
      "name": "CLARKE QUAY",
      "plugTypes": [
        {
          "plugType": "Combo 2",
          "price": "0.8938",
          "current": "DC",
          "powerRating": "50",
          "priceType": "kWh",
          "evIds": [
            {
              "evCpId": "R114858R-001",
              "status": "1"
            },
            {
              "evCpId": "R114858R-002",
              "status": "1"
            }
          ]
        }
      ]
    }
  ]
}

### Branch 1: Flatten the nested table with 3 x pd.json_normalize()

#### First Normalize

Begin flatten the first level from 'chargingPoints' **with json.normalize()**. It will bring out the individual charging points at each location  to 1 row each and give a new index (as oppose to explode)

In [7]:
ev_df_charging_point =pd.json_normalize(
        ev_data['evLocationsData'],
        record_path=['chargingPoints'],
        meta=[
            'address', 
            'name', 
            'longtitude', 
            'latitude', 
            'postalCode'         
        ],
        meta_prefix="point_")
#normalize to bring item in the plugtype list to reflect more information as a column

display(ev_df_charging_point.head())

,status,operatingHours,operator,position,name,plugTypes,point_address,point_name,point_longtitude,point_latitude,point_postalCode
0,1,,SP MOBILITY PTE. LTD.,L4 50,CLARKE QUAY,"[{'plugType': 'Type 2', 'price': '0.8066', 'cu...",3E RIVER VALLEY ROAD SINGAPORE 179024,CLARKE QUAY,103.846728,1.290314,179024
1,1,,SP MOBILITY PTE. LTD.,L4 49,CLARKE QUAY,"[{'plugType': 'Type 2', 'price': '0.8066', 'cu...",3E RIVER VALLEY ROAD SINGAPORE 179024,CLARKE QUAY,103.846728,1.290314,179024
2,1,,SP MOBILITY PTE. LTD.,L4 51 & 52,CLARKE QUAY,"[{'plugType': 'Combo 2', 'price': '0.8938', 'c...",3E RIVER VALLEY ROAD SINGAPORE 179024,CLARKE QUAY,103.846728,1.290314,179024
3,1,,STRIDES YTL PTE. LTD.,L3A 129,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,"[{'plugType': 'Type 2', 'price': '0.6980', 'cu...",142A PASIR RIS STREET 11 SINGAPORE 511142,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,103.959758,1.362839,511142
4,1,,STRIDES YTL PTE. LTD.,L3A 127,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,"[{'plugType': 'Type 2', 'price': '0.6980', 'cu...",142A PASIR RIS STREET 11 SINGAPORE 511142,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,103.959758,1.362839,511142

#### Second Normalize - plugTypes

Based on the result of the first normalized result - ev_df_charging_point_info, we have another list inside the **'plugTypes'** column, which contain the plug info. To further bring out plugtype info, we normalize again to bring out the info on each charging point.

The **'plugType'** dictionary is enclosed in list in the column, performing a simple normalize will not be able to extract the dictionary. **to_dict** is used to convert the entire table to dictionary, which is an acceptable form for the parameter in normalize.

In [8]:
ev_df_charging_point_plugtype= pd.json_normalize(ev_df_charging_point.to_dict('records'), 
               record_path=['plugTypes'],
                meta=[
                    'point_name',
                    'point_address',
                    'point_postalCode',
                    'point_longtitude',
                    'point_latitude',
                    'name',
                    'position',
                    'status',
                    'operatingHours',
                    'operator',
                ],
        meta_prefix="plug_")
display(ev_df_charging_point_plugtype.head())

,plugType,price,current,powerRating,priceType,evIds,plug_point_name,plug_point_address,plug_point_postalCode,plug_point_longtitude,plug_point_latitude,plug_name,plug_position,plug_status,plug_operatingHours,plug_operator
0,Type 2,0.8066,AC,22,kWh,"[{'evCpId': 'R114861R-001', 'status': '1'}]",CLARKE QUAY,3E RIVER VALLEY ROAD SINGAPORE 179024,179024,103.846728,1.290314,CLARKE QUAY,L4 50,1,,SP MOBILITY PTE. LTD.
1,Type 2,0.8066,AC,22,kWh,"[{'evCpId': 'R114859D-001', 'status': '1'}]",CLARKE QUAY,3E RIVER VALLEY ROAD SINGAPORE 179024,179024,103.846728,1.290314,CLARKE QUAY,L4 49,1,,SP MOBILITY PTE. LTD.
2,Combo 2,0.8938,DC,50,kWh,"[{'evCpId': 'R114858R-001', 'status': '1'}, {'...",CLARKE QUAY,3E RIVER VALLEY ROAD SINGAPORE 179024,179024,103.846728,1.290314,CLARKE QUAY,L4 51 & 52,1,,SP MOBILITY PTE. LTD.
3,Type 2,0.6980,AC,7.4,kWh,"[{'evCpId': 'R122902D-001', 'status': '1'}]",BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,142A PASIR RIS STREET 11 SINGAPORE 511142,511142,103.959758,1.362839,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,L3A 129,1,,STRIDES YTL PTE. LTD.
4,Type 2,0.6980,AC,7.4,kWh,"[{'evCpId': 'R122900G-001', 'status': '1'}]",BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,142A PASIR RIS STREET 11 SINGAPORE 511142,511142,103.959758,1.362839,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,L3A 127,1,,STRIDES YTL PTE. LTD.

#### Third Normalize Aka Last

After normalizing the result, we need to further unpack the list within the evID, to add more information on this charging point's status. Similar to the above plugType column, the evIDs column is also dictionary in a list. We used the **to_dict** again to deal with the list.

As we have to include the parent details in the newly expanded rows, we take the chance to re-arrange the columns through meta starting from the bigger picture of location before zooming into charging point then to more information on charging points

In [9]:
ev_df_flattened=pd.json_normalize(ev_df_charging_point_plugtype.to_dict('records'), 
                             record_path =['evIds'],
                            meta=
                             ['plug_point_name',
                              'plug_point_address',
                              'plug_point_postalCode',
                              'plug_point_longtitude',
                              'plug_point_latitude',
                              'plug_name',
                              'plug_position',
                              'plug_status',
                              'plug_operatingHours',
                              'plug_operator',
                              'plugType',
                              'powerRating',
                              'current',
                              'price',
                              'priceType',
                              ])
display(ev_df_flattened.head())

,evCpId,status,plug_point_name,plug_point_address,plug_point_postalCode,plug_point_longtitude,plug_point_latitude,plug_name,plug_position,plug_status,plug_operatingHours,plug_operator,plugType,powerRating,current,price,priceType
0,R114861R-001,1,CLARKE QUAY,3E RIVER VALLEY ROAD SINGAPORE 179024,179024,103.846728,1.290314,CLARKE QUAY,L4 50,1,,SP MOBILITY PTE. LTD.,Type 2,22,AC,0.8066,kWh
1,R114859D-001,1,CLARKE QUAY,3E RIVER VALLEY ROAD SINGAPORE 179024,179024,103.846728,1.290314,CLARKE QUAY,L4 49,1,,SP MOBILITY PTE. LTD.,Type 2,22,AC,0.8066,kWh
2,R114858R-001,1,CLARKE QUAY,3E RIVER VALLEY ROAD SINGAPORE 179024,179024,103.846728,1.290314,CLARKE QUAY,L4 51 & 52,1,,SP MOBILITY PTE. LTD.,Combo 2,50,DC,0.8938,kWh
3,R114858R-002,1,CLARKE QUAY,3E RIVER VALLEY ROAD SINGAPORE 179024,179024,103.846728,1.290314,CLARKE QUAY,L4 51 & 52,1,,SP MOBILITY PTE. LTD.,Combo 2,50,DC,0.8938,kWh
4,R122902D-001,1,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,142A PASIR RIS STREET 11 SINGAPORE 511142,511142,103.959758,1.362839,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,L3A 129,1,,STRIDES YTL PTE. LTD.,Type 2,7.4,AC,0.6980,kWh

#### Check

There is no more further to unpack. Below is to check if we have fully unpacked all the values inside the list of dictionaries in each columns.

In [10]:
display(ev_df_flattened.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11310 entries, 0 to 11309
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   evCpId                 11310 non-null  object
 1   status                 11310 non-null  object
 2   plug_point_name        11310 non-null  object
 3   plug_point_address     11310 non-null  object
 4   plug_point_postalCode  11310 non-null  object
 5   plug_point_longtitude  11310 non-null  object
 6   plug_point_latitude    11310 non-null  object
 7   plug_name              11310 non-null  object
 8   plug_position          11310 non-null  object
 9   plug_status            11310 non-null  object
 10  plug_operatingHours    11310 non-null  object
 11  plug_operator          11310 non-null  object
 12  plugType               11310 non-null  object
 13  powerRating            11310 non-null  object
 14  current                11310 non-null  object
 15  price                  11310 non-null  object
 16  priceType              11310 non-null  object
dtypes: object(17)
memory usage: 1.5+ MB

None

### Branch 2: pd.json_normalize() + 1 Loop

In [85]:
ev_locations = ev_data["evLocationsData"]

In [86]:
ev_df = pd.json_normalize(ev_locations)
ev_df.head()

,address,name,longtitude,latitude,postalCode,chargingPoints
0,142A PASIR RIS STREET 11 SINGAPORE 511142,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,103.959758,1.362839,511142,"[{'status': '0', 'operatingHours': '', 'operat..."
1,3E RIVER VALLEY ROAD SINGAPORE 179024,CLARKE QUAY,103.846728,1.290314,179024,"[{'status': '1', 'operatingHours': '', 'operat..."
2,207A BISHAN STREET 23 SINGAPORE 571207,BLK 207A BISHAN STREET 23,103.848309,1.355154,571207,"[{'status': '1', 'operatingHours': '', 'operat..."
3,113 BUKIT BATOK WEST AVENUE 6 SINGAPORE 650113,BLK 111/132 BUKIT BATOK WEST AVENUE 6,103.746309,1.349872,650113,"[{'status': '1', 'operatingHours': '', 'operat..."
4,640A JURONG WEST STREET 61 SINGAPORE 641640,BLK 640A JURONG WEST STREET 61 MULTI STOREY CA...,103.696043,1.339733,641640,"[{'status': '100', 'operatingHours': '', 'oper..."

Location
 ──> Charging Point
      ──> Plug Type
           ──> EV ID

In [87]:
# The API response contains multiple levels of nested arrays (chargingPoints, plugTypes, and evIds).
# Nested loops are used to explicitly iterate through each level and construct one row per EV charging point,
# while retaining the parent location and charging-point attributes.

rows = []

for location in ev_locations:
    for charging_point in location["chargingPoints"]:
        for plug in charging_point["plugTypes"]:
            for ev_id in plug["evIds"]:
                rows.append({
                    "address": location["address"],
                    "name": location["name"],
                    "postalCode": location["postalCode"],
                    "latitude": location["latitude"],
                    "longitude": location["longtitude"],
                    "operator": charging_point["operator"],
                    "position": charging_point["position"],
                    "plugType": plug["plugType"],
                    "current": plug["current"],
                    "powerRating": plug["powerRating"],
                    "price": plug["price"],
                    "priceType": plug["priceType"],
                    "evCpId": ev_id["evCpId"],
                    "status": ev_id["status"]
                })

ev_df = pd.DataFrame(rows)
print(ev_df.shape)

(11308, 14)

### Branch 3: pd.json_normalize within for Loop + 1 final Loop

In [88]:
# Use pd.json_normalize to flatten 'evLocationsData' → 'attributes' into a DataFrame

df_location = pd.json_normalize(ev_data, 'evLocationsData')

print(f"Shape : {df_location.shape}")
df_location.head(5)

Shape : (2730, 6)

,address,name,longtitude,latitude,postalCode,chargingPoints
0,142A PASIR RIS STREET 11 SINGAPORE 511142,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,103.959758,1.362839,511142,"[{'status': '0', 'operatingHours': '', 'operat..."
1,3E RIVER VALLEY ROAD SINGAPORE 179024,CLARKE QUAY,103.846728,1.290314,179024,"[{'status': '1', 'operatingHours': '', 'operat..."
2,207A BISHAN STREET 23 SINGAPORE 571207,BLK 207A BISHAN STREET 23,103.848309,1.355154,571207,"[{'status': '1', 'operatingHours': '', 'operat..."
3,113 BUKIT BATOK WEST AVENUE 6 SINGAPORE 650113,BLK 111/132 BUKIT BATOK WEST AVENUE 6,103.746309,1.349872,650113,"[{'status': '1', 'operatingHours': '', 'operat..."
4,640A JURONG WEST STREET 61 SINGAPORE 641640,BLK 640A JURONG WEST STREET 61 MULTI STOREY CA...,103.696043,1.339733,641640,"[{'status': '100', 'operatingHours': '', 'oper..."

In [89]:
# Use pd.json_normalize to flatten 'chargingPoints' → 'attributes' into a DataFrame

df_chargingpoints = pd.json_normalize(ev_data['evLocationsData'], 'chargingPoints')

print(f"Shape : {df_chargingpoints.shape}")
df_chargingpoints.head(5)

Shape : (8904, 6)

,status,operatingHours,operator,position,name,plugTypes
0,0,,STRIDES YTL PTE. LTD.,L3A 128,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,"[{'plugType': 'Type 2', 'price': '0.6980', 'cu..."
1,1,,STRIDES YTL PTE. LTD.,L3A 127,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,"[{'plugType': 'Type 2', 'price': '0.6980', 'cu..."
2,0,,STRIDES YTL PTE. LTD.,L3A 129,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,"[{'plugType': 'Type 2', 'price': '0.6980', 'cu..."
3,1,,SP MOBILITY PTE. LTD.,L4 49,CLARKE QUAY,"[{'plugType': 'Type 2', 'price': '0.8066', 'cu..."
4,1,,SP MOBILITY PTE. LTD.,L4 51 & 52,CLARKE QUAY,"[{'plugType': 'Combo 2', 'price': '0.8938', 'c..."

In [90]:
# Use pd.json_normalize to flatten 'plugTypes' → 'attributes' into a DataFrame

dfs_plugtype = []

for i in range(len(ev_data['evLocationsData'])):
    for j in range(len(ev_data['evLocationsData'][i]['chargingPoints'])):
        df1 = pd.json_normalize(
            ev_data['evLocationsData'][i]['chargingPoints'][j],
            'plugTypes'
        )
        dfs_plugtype.append(df1)

df_plugtype = pd.concat(dfs_plugtype, ignore_index=True)

print(f"Shape : {df_plugtype.shape}")
df_plugtype.head(5)

Shape : (9157, 6)

,plugType,price,current,powerRating,priceType,evIds
0,Type 2,0.6980,AC,7.4,kWh,"[{'evCpId': 'R122901R-001', 'status': '0'}]"
1,Type 2,0.6980,AC,7.4,kWh,"[{'evCpId': 'R122900G-001', 'status': '1'}]"
2,Type 2,0.6980,AC,7.4,kWh,"[{'evCpId': 'R122902D-001', 'status': '0'}]"
3,Type 2,0.8066,AC,22,kWh,"[{'evCpId': 'R114859D-001', 'status': '1'}]"
4,Combo 2,0.8938,DC,50,kWh,"[{'evCpId': 'R114858R-001', 'status': '1'}, {'..."

In [21]:
# Use pd.json_normalize to flatten 'evIds' → 'attributes' into a DataFrame

dfs_evids = []

for i in range(len(ev_data['evLocationsData'])):
    for j in range(len(ev_data['evLocationsData'][i]['chargingPoints'])):
        for k in range(len(ev_data['evLocationsData'][i]['chargingPoints'][j]['plugTypes'])):
            df2 = pd.json_normalize(
                ev_data['evLocationsData'][i]['chargingPoints'][j]['plugTypes'][k],
                'evIds'
                )
            dfs_evids.append(df2)

df_evids = pd.concat(dfs_evids, ignore_index=True)

print(f"Shape : {df_evids.shape}")
#df_evids.head(5)

Shape : (11308, 2)

In [92]:
# use for loop to flatten out all the nested structure and combine all into 1 big table

records = []

for location in ev_data['evLocationsData']:
    
    for charging_point in location['chargingPoints']:
        
        for plug_type in charging_point['plugTypes']:
            
            for ev_id in plug_type['evIds']:
                
                record = {
                    'address': location['address'],
                    'location_name': location['name'],
                    'longtitude': location['longtitude'],
                    'latitude': location['latitude'],
                    'postal_code': location['postalCode'],
                    
                    'chargingpoint_status': charging_point['status'],
                    'operating_hours': charging_point['operatingHours'],
                    'operator': charging_point['operator'],
                    'position': charging_point['position'],
                    'chargingpoint_name': charging_point['name'],
                    
                    'plug_type': plug_type['plugType'],
                    'price': plug_type['price'],
                    'current': plug_type['current'],
                    'power_rating': plug_type['powerRating'],
                    'price_type': plug_type['priceType'],
                    
                    'evcp_id': ev_id['evCpId'],
                    'evid_status': ev_id['status']
                }
                
                records.append(record)

df_main = pd.DataFrame(records)

print(f"Shape : {df_main.shape}")
df_main.head(5)

Shape : (11308, 17)

,address,location_name,longtitude,latitude,postal_code,chargingpoint_status,operating_hours,operator,position,chargingpoint_name,plug_type,price,current,power_rating,price_type,evcp_id,evid_status
0,142A PASIR RIS STREET 11 SINGAPORE 511142,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,103.959758,1.362839,511142,0,,STRIDES YTL PTE. LTD.,L3A 128,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,Type 2,0.6980,AC,7.4,kWh,R122901R-001,0
1,142A PASIR RIS STREET 11 SINGAPORE 511142,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,103.959758,1.362839,511142,1,,STRIDES YTL PTE. LTD.,L3A 127,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,Type 2,0.6980,AC,7.4,kWh,R122900G-001,1
2,142A PASIR RIS STREET 11 SINGAPORE 511142,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,103.959758,1.362839,511142,0,,STRIDES YTL PTE. LTD.,L3A 129,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,Type 2,0.6980,AC,7.4,kWh,R122902D-001,0
3,3E RIVER VALLEY ROAD SINGAPORE 179024,CLARKE QUAY,103.846728,1.290314,179024,1,,SP MOBILITY PTE. LTD.,L4 49,CLARKE QUAY,Type 2,0.8066,AC,22,kWh,R114859D-001,1
4,3E RIVER VALLEY ROAD SINGAPORE 179024,CLARKE QUAY,103.846728,1.290314,179024,1,,SP MOBILITY PTE. LTD.,L4 51 & 52,CLARKE QUAY,Combo 2,0.8938,DC,50,kWh,R114858R-001,1

### Branch 4: Break into 4 tables

In [93]:
# Create empty lists
locations = []
charging_points = []
plug_types = []
ev_ids = []

In [94]:
# Convert the nested JSON into four tables
charging_point_id = 1
plug_type_id = 1
ev_id = 1

for location_id, location in enumerate(
    ev_data['evLocationsData'], start=1
):
    
    # -----------------------------
    # LOCATION
    # -----------------------------
    locations.append({
        'location_id': location_id,
        'address': location['address'],
        'name': location['name'],
        'longitude': location['longtitude'],
        'latitude': location['latitude'],
        'postal_code': location['postalCode']
    })
    
    
    # -----------------------------
    # CHARGING POINT
    # -----------------------------
    for charging_point in location['chargingPoints']:
        
        current_charging_point_id = charging_point_id
        
        charging_points.append({
            'charging_point_id': current_charging_point_id,
            'location_id': location_id,
            'status': charging_point['status'],
            'operating_hours': charging_point['operatingHours'],
            'operator': charging_point['operator'],
            'position': charging_point['position'],
            'name': charging_point['name']
        })
        
        charging_point_id += 1
        
        
        # -----------------------------
        # PLUG TYPE
        # -----------------------------
        for plug_type in charging_point['plugTypes']:
            
            current_plug_type_id = plug_type_id
            
            plug_types.append({
                'plug_type_id': current_plug_type_id,
                'charging_point_id': current_charging_point_id,
                'plug_type': plug_type['plugType'],
                'price': plug_type['price'],
                'current': plug_type['current'],
                'power_rating': plug_type['powerRating'],
                'price_type': plug_type['priceType']
            })
            
            plug_type_id += 1
            
            
            # -----------------------------
            # EV CHARGING ID
            # -----------------------------
            for ev in plug_type['evIds']:
                
                ev_ids.append({
                    'ev_id': ev_id,
                    'plug_type_id': current_plug_type_id,
                    'ev_cp_id': ev['evCpId'],
                    'status': ev['status']
                })
                
                ev_id += 1

In [95]:
# Create the four Pandas DataFrames
ev_location_df = pd.DataFrame(locations)

charging_point_df = pd.DataFrame(charging_points)

plug_type_df = pd.DataFrame(plug_types)

ev_charging_id_df = pd.DataFrame(ev_ids)

### [TRANSFORMATION ]

Explore the data to get a sense

In [42]:
ev_df_flattened.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11310 entries, 0 to 11309
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   evCpId                 11310 non-null  object
 1   status                 11310 non-null  object
 2   plug_point_name        11310 non-null  object
 3   plug_point_address     11310 non-null  object
 4   plug_point_postalCode  11310 non-null  object
 5   plug_point_longtitude  11310 non-null  object
 6   plug_point_latitude    11310 non-null  object
 7   plug_name              11310 non-null  object
 8   plug_position          11310 non-null  object
 9   plug_status            11310 non-null  object
 10  plug_operatingHours    11310 non-null  object
 11  plug_operator          11310 non-null  object
 12  plugType               11310 non-null  object
 13  powerRating            11310 non-null  object
 14  current                11310 non-null  object
 15  price                  11310 non-null  object
 16  priceType              11310 non-null  object
dtypes: object(17)
memory usage: 1.5+ MB

#### Rearranging & Renaming

In [15]:
ev_df_final= ev_df_flattened.reindex(columns= ['plug_point_name', 'plug_point_address', 'plug_point_postalCode', 'plug_point_longtitude', 'plug_point_latitude', 'plug_name', 'plug_position', 'plug_status', 'plug_operatingHours', 'plug_operator', 'plugType', 'powerRating', 'current',	'price', 'priceType', 'evCpId', 'status'])
ev_df_final.columns = ['point_location', 'point_address', 'postal_code', 'longtitude', 'latitude', 'plug_location', 'plug_position', 'plug_status', 'plug_operating_hours', 'plug_operator', 'plug_type', 'power_rating', 'current',	'price', 'price_unit', 'evcp_id', 'evcp_status']
ev_df_final[:6]

,point_location,point_address,postal_code,longtitude,latitude,plug_location,plug_position,plug_status,plug_operating_hours,plug_operator,plug_type,power_rating,current,price,price_unit,evcp_id,evcp_status
0,CLARKE QUAY,3E RIVER VALLEY ROAD SINGAPORE 179024,179024,103.846728,1.290314,CLARKE QUAY,L4 50,1,,SP MOBILITY PTE. LTD.,Type 2,22,AC,0.8066,kWh,R114861R-001,1
1,CLARKE QUAY,3E RIVER VALLEY ROAD SINGAPORE 179024,179024,103.846728,1.290314,CLARKE QUAY,L4 49,1,,SP MOBILITY PTE. LTD.,Type 2,22,AC,0.8066,kWh,R114859D-001,1
2,CLARKE QUAY,3E RIVER VALLEY ROAD SINGAPORE 179024,179024,103.846728,1.290314,CLARKE QUAY,L4 51 & 52,1,,SP MOBILITY PTE. LTD.,Combo 2,50,DC,0.8938,kWh,R114858R-001,1
3,CLARKE QUAY,3E RIVER VALLEY ROAD SINGAPORE 179024,179024,103.846728,1.290314,CLARKE QUAY,L4 51 & 52,1,,SP MOBILITY PTE. LTD.,Combo 2,50,DC,0.8938,kWh,R114858R-002,1
4,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,142A PASIR RIS STREET 11 SINGAPORE 511142,511142,103.959758,1.362839,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,L3A 129,1,,STRIDES YTL PTE. LTD.,Type 2,7.4,AC,0.6980,kWh,R122902D-001,1
5,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,142A PASIR RIS STREET 11 SINGAPORE 511142,511142,103.959758,1.362839,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,L3A 127,1,,STRIDES YTL PTE. LTD.,Type 2,7.4,AC,0.6980,kWh,R122900G-001,1

#### Check for columns with duplicate values

Before dropping, do a check to confirm if it is duplicates

##### <u> Potential Duplicates 1: plug status cs evcp status

In [16]:
ev_status_duplicate_check = ev_df_final['plug_status']==ev_df_final['evcp_status']
print(ev_status_duplicate_check.value_counts())

True     10602
False      708
Name: count, dtype: int64

In [17]:
#The two columns are not duplicates, to confirm by checking the actual values: 
ev_status_duplicate_examine = ev_df_final[ev_df_final['plug_status']!=ev_df_final['evcp_status']]
print(ev_status_duplicate_examine['plug_status'].value_counts())

plug_status
1      572
100    129
0        7
Name: count, dtype: int64

In [18]:
print(ev_status_duplicate_examine['evcp_status'].value_counts())

evcp_status
0    495
     213
Name: count, dtype: int64

Both columns have different values.  
To **retain** the columns. 

Note: 
Cross-reference with LTA documentation (page 49,50) confirms plug status values ('1','100','0')and evcp status('0','') are valid.  

---

##### <u> Potential Duplicates 2: point location vs plug location

In [19]:
plug_point_location_duplicate_check = ev_df_final['point_location']==ev_df_final['plug_location']
print(plug_point_location_duplicate_check.value_counts())

True     10694
False      616
Name: count, dtype: int64

In [21]:
plug_point_location_duplicate_examine = ev_df_final[ev_df_final['point_location']!=ev_df_final['plug_location']] #to verify the differences
print(plug_point_location_duplicate_examine['point_location'].value_counts())

point_location
MULTI STOREY CAR PARK                    36
                                         35
BLK 32/35 TELOK BLANGAH RISE             16
DBS SINGAPORE EXPO                       14
SKH MEDICAL CENTRE                       12
                                         ..
ST MICROELECTRONICS BHQ                   1
NEW TECH PARK                             1
CITIBANK UE SQUARE                        1
MARINA BAY FINANCIAL CENTRE (TOWER 1)     1
ORANGE VALLEY NURSING HOME (SIMEI)        1
Name: count, Length: 150, dtype: int64

In [22]:
print(plug_point_location_duplicate_examine['plug_location'].value_counts()) # to verify the differences

plug_location
MULTI STOREY CAR PARK                 17
BLK 29/32 TELOK BLANGAH RISE          16
                                      16
SINGAPORE EXPO                        14
BLK 704-714 CLEMENTI WEST STREET 2    12
                                      ..
THE STAR VISTA                         1
BLK 215 ANG MO KIO STREET 22           1
IKEA FOOD CENTRE                       1
ALEXANDRA HOSPITAL                     1
DBS MARINA BAY LINK MALL               1
Name: count, Length: 171, dtype: int64

Both columns have different values.  
To **retain** the columns.   

Note:
- **plug_location**: Nulls exist  
- **point_location**: Nulls exist  

We will be cleaning the blanks in the next few steps

---

##### <u> Potential Duplicates 3: point location vs point address

Note: 
_point location and point address are very similar, as we can tell from the first few entries. Check if we are able to <Mark> replace the data by inferring  point location from postal code later._

---

#### Data Cleaning

##### <u> Check for nulls

In [23]:
ev_df_final.isnull().sum()

point_location          0
point_address           0
postal_code             0
longtitude              0
latitude                0
plug_location           0
plug_position           0
plug_status             0
plug_operating_hours    0
plug_operator           0
plug_type               0
power_rating            0
current                 0
price                   0
price_unit              0
evcp_id                 0
evcp_status             0
dtype: int64

In [24]:
ev_df_final.isna().sum()

point_location          0
point_address           0
postal_code             0
longtitude              0
latitude                0
plug_location           0
plug_position           0
plug_status             0
plug_operating_hours    0
plug_operator           0
plug_type               0
power_rating            0
current                 0
price                   0
price_unit              0
evcp_id                 0
evcp_status             0
dtype: int64

Note: 

- Expected a row of null values on 'operatingHours' column through the earlier visual check where the entire operating hours shows empty, but df.isnull/isna shows no sign of nulls, likely to be empty strings which is not picked up

In [25]:
print(ev_df_final['plug_operating_hours'].value_counts()) #it is blank space, and all 11308 are empty.

plug_operating_hours
    11310
Name: count, dtype: int64

Since there is no meaningful values in plug_operating_hours, we will drop this column

In [26]:
ev_df_final.drop(columns ='plug_operating_hours', inplace=True)

---

##### <u> Double check values for nulls

In [28]:
print(ev_df_final['point_location'].value_counts(dropna=False))
print()
print(ev_df_final['postal_code'].value_counts(dropna=False))
print()
print(ev_df_final['plug_location'].value_counts(dropna=False))
print()
print(ev_df_final['plug_position'].value_counts(dropna=False))
print()
print(ev_df_final['plug_status'].value_counts(dropna=False))
print()
print(ev_df_final['plug_operator'].value_counts(dropna=False))
print()
print(ev_df_final['plug_type'].value_counts(dropna=False)) # dropna=False - count missing values (NaN)
print()
print(ev_df_final['power_rating'].value_counts(dropna=False))
print()
print(ev_df_final['current'].value_counts(dropna=False))
print()
print(ev_df_final['price_unit'].value_counts(dropna=False))
print()
print(ev_df_final['evcp_id'].value_counts(dropna=False))
print()
print(ev_df_final['evcp_status'].value_counts(dropna=False))

point_location
                                                            464
MULTI STOREY CAR PARK                                       123
SETSCO @ JALAN PAPAN                                         78
GREAT WORLD CITY                                             64
GOLDEN VILLAGE (GV SUNTEC CITY)                              28
                                                           ...
CIMB PLAZA                                                    1
BLK 278-281 BISHAN STREET 24                                  1
24-HOUR WALK-IN CLINIC (MOUNT ELIZABETH NOVENA HOSPITAL)      1
OXLEY TOWER                                                   1
SELETAR AIRPORT PASSENGER TERMINAL                            1
Name: count, Length: 2545, dtype: int64

postal_code
619835    78
237994    64
758060    28
529757    28
038983    28
          ..
329928     1
758118     1
199597     1
797405     1
348574     1
Name: count, Length: 2731, dtype: int64

plug_location
                                    445
MULTI STOREY CAR PARK               104
SETSCO @ JALAN PAPAN                 78
GREAT WORLD CITY                     60
TEMASEK POLYTECHNIC                  20
                                   ...
DBS MARINA BAY LINK MALL              1
BUKIT BATOK TRANSMITTING STATION      1
CT HUB                                1
DBS MBFC BRANCH                       1
ATM DBS VIVOCITY                      1
Name: count, Length: 2695, dtype: int64

plug_position
L1 -                        408
L2 -                        124
L01 INSIDE SHELL STATION     54
L1 1                         49
L1 2                         44
                           ...
L4 349                        1
L1 475                        1
L1 476                        1
L1 477                        1
L4 50                         1
Name: count, Length: 4242, dtype: int64

plug_status
1      9844
0      1337
100     129
Name: count, dtype: int64

plug_operator
SP MOBILITY PTE. LTD.                     2652
CHARGE+ PTE. LTD.                         2569
COMFORTDELGRO ENGIE PTE. LTD.             2069
SHELL SINGAPORE PTE. LTD.                 1825
STRIDES YTL PTE. LTD.                     1124
VOLT SINGAPORE PTE. LTD.                   338
MNL SOLUTIONS PTE. LTD.                    104
GREAT CHARGE PTE. LTD.                      84
FASTPARKNCHARGE PTE. LTD.                   69
EV MOBILITY PTE. LTD.                       61
TESLA MOTORS SINGAPORE PRIVATE LIMITED      59
KED ENERGY PTE. LTD.                        57
NOVOWATT PTE. LTD.                          50
EIGEN ENERGY PTE. LTD.                      46
BUSWAYS PTE. LTD.                           34
ST ENGINEERING URBAN SOLUTIONS LTD.         31
EVONE CHARGING PTE. LTD.                    23
CITY ENERGY GO PTE. LTD.                    21
SOLATEKS PTE. LTD.                          20
UP SOLUTIONS PTE. LTD.                      17
AIRETEC PTE. LTD.                           11
ENEREADY PTE. LTD.                          11
UNION GAS PTE. LTD.                         10
WES CARES ENERGY PTE. LTD.                   9
G. TECH PTE. LTD.                            5
ELECTRIC PTE. LTD.                           4
IWOW TECHNOLOGY LIMITED                      4
P-Parking International Pte Ltd              2
ALPINA ENERGY PTE. LTD.                      1
Name: count, dtype: int64

plug_type
Type 2     9810
Combo 2    1498
CHAdeMO       2
Name: count, dtype: int64

power_rating
7.4    4723
7      2785
22     1503
3.7     534
120     438
100     266
50      227
43      175
60      164
180     148
11       76
30       62
250      40
160      38
480      34
190      32
80       20
40       13
150      10
240      10
24        4
90        2
7.3       2
200       2
44        2
Name: count, dtype: int64

current
AC    9810
DC    1500
Name: count, dtype: int64

price_unit
kWh     10898
          255
h         156
free        1
Name: count, dtype: int64

evcp_id
R114861R-001    1
R125677D-001    1
R114226Z-002    1
R114229R-001    1
R114229R-002    1
               ..
R126115R-001    1
R126115R-002    1
R126117H-002    1
R126117H-001    1
R127131F-001    1
Name: count, Length: 11310, dtype: int64

evcp_status
1    9272
0    1825
      213
Name: count, dtype: int64

Cross reference with LTA documentation (page 49,50) confirms there are no invalid values.  

**Note:  
<u> plug status according to the LTA documentation: 
- '0':Occupied. All charging points are occupied    
- '1':Available. At least 1 charging point is available i.e at least one evId status is 1.    
- '100': Not available. All evId statuses are ''.  

<u> evID status according to the LTA documentation:
- '0':Occupied. Charging / reserved / blocked    
- '1':Available. At least 1 charging point is available i.e at least one evId status is 1.    
- '': Not available. out of order / in operative / unknown / planned / removed.  

<u> power_rating:   
- To round off to 1 decimal point later

##### <u> Check for double space '  ' white space in the cell

As null does not show up on isnull, we are using double spaces in a string to detect the blank cell.

In [29]:
for columns in ev_df_final.columns:
    blank = ev_df_final[columns].astype(str).str.contains('  ').any()
    print(f'{columns}: {blank}' )

point_location: True
point_address: False
postal_code: False
longtitude: False
latitude: False
plug_location: True
plug_position: True
plug_status: False
plug_operator: False
plug_type: False
power_rating: False
current: False
price: False
price_unit: False
evcp_id: False
evcp_status: False

In [30]:
print('Count of double space - white space')
print(f'Point Location: {len(ev_df_final[ev_df_final['point_location'].astype(str).str.contains('  ')])}') 
print(f'Plug_location: {len(ev_df_final[ev_df_final['plug_location'].astype(str).str.contains('  ')])}')
print(f'Plug_position: {len(ev_df_final[ev_df_final['plug_position'].astype(str).str.contains('  ')])}')

Count of double space - white space
Point Location: 20
Plug_location: 19
Plug_position: 2

<mark>We will ignore point location as we will be replacing this column with inference from the postalcode later_

We do a strip() first in case our double spacing criteria ('  ') shows up for cell value with trailing space (not what we wanted).

In [31]:
for columns in ev_df_final.columns:
    ev_df_final[columns] = ev_df_final[columns].astype(str).str.strip()
    blank2 = ev_df_final[columns].astype(str).str.contains('  ').any()
    print(f'{columns}: {blank}' )

point_location: False
point_address: False
postal_code: False
longtitude: False
latitude: False
plug_location: False
plug_position: False
plug_status: False
plug_operator: False
plug_type: False
power_rating: False
current: False
price: False
price_unit: False
evcp_id: False
evcp_status: False

There are no more '  '(double white space) in the cells. All records are due to trailing spaces.

##### <u>Check for '' values in the columns

('  ') Double spaces does not account for the white space in point location and plug location. To try out '' values in the columns. 
Since we need to check through for 16 columns, it is suitable to do a function here

In [32]:
def null_check(column, table):
    blanks = (table[column] == '').sum()
    return print(f'blanks in {column}:{blanks}')

def replace_empty(column, table):
    table[column] = table[column].replace('', np.nan)
    return table

Repeat the checking and replacing of '' value using loop

In [33]:
for each_col in ev_df_final.columns:
    null_check(column= each_col, table=ev_df_final)
    replace_empty(column= each_col, table=ev_df_final)
    null_check(column= each_col, table=ev_df_final)

blanks in point_location:464
blanks in point_location:0
blanks in point_address:0
blanks in point_address:0
blanks in postal_code:0
blanks in postal_code:0
blanks in longtitude:0
blanks in longtitude:0
blanks in latitude:0
blanks in latitude:0
blanks in plug_location:445
blanks in plug_location:0
blanks in plug_position:0
blanks in plug_position:0
blanks in plug_status:0
blanks in plug_status:0
blanks in plug_operator:0
blanks in plug_operator:0
blanks in plug_type:0
blanks in plug_type:0
blanks in power_rating:0
blanks in power_rating:0
blanks in current:0
blanks in current:0
blanks in price:217
blanks in price:0
blanks in price_unit:255
blanks in price_unit:0
blanks in evcp_id:0
blanks in evcp_id:0
blanks in evcp_status:213
blanks in evcp_status:0

('') shows up in 'Point location' and plug location - the blank spaces detected earlier belongs to ('') in the cell. Successfully replaced ('') with np.nan.

In [35]:
ev_df_final.duplicated().sum()

np.int64(0)

#### Changing Data type

Inspect current data type

In [36]:
ev_df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11310 entries, 0 to 11309
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   point_location  10846 non-null  object
 1   point_address   11310 non-null  object
 2   postal_code     11310 non-null  object
 3   longtitude      11310 non-null  object
 4   latitude        11310 non-null  object
 5   plug_location   10865 non-null  object
 6   plug_position   11310 non-null  object
 7   plug_status     11310 non-null  object
 8   plug_operator   11310 non-null  object
 9   plug_type       11310 non-null  object
 10  power_rating    11310 non-null  object
 11  current         11310 non-null  object
 12  price           11093 non-null  object
 13  price_unit      11055 non-null  object
 14  evcp_id         11310 non-null  object
 15  evcp_status     11097 non-null  object
dtypes: object(16)
memory usage: 1.4+ MB

In [37]:
ev_df_final.head()

,point_location,point_address,postal_code,longtitude,latitude,plug_location,plug_position,plug_status,plug_operator,plug_type,power_rating,current,price,price_unit,evcp_id,evcp_status
0,CLARKE QUAY,3E RIVER VALLEY ROAD SINGAPORE 179024,179024,103.846728,1.290314,CLARKE QUAY,L4 50,1,SP MOBILITY PTE. LTD.,Type 2,22,AC,0.8066,kWh,R114861R-001,1
1,CLARKE QUAY,3E RIVER VALLEY ROAD SINGAPORE 179024,179024,103.846728,1.290314,CLARKE QUAY,L4 49,1,SP MOBILITY PTE. LTD.,Type 2,22,AC,0.8066,kWh,R114859D-001,1
2,CLARKE QUAY,3E RIVER VALLEY ROAD SINGAPORE 179024,179024,103.846728,1.290314,CLARKE QUAY,L4 51 & 52,1,SP MOBILITY PTE. LTD.,Combo 2,50,DC,0.8938,kWh,R114858R-001,1
3,CLARKE QUAY,3E RIVER VALLEY ROAD SINGAPORE 179024,179024,103.846728,1.290314,CLARKE QUAY,L4 51 & 52,1,SP MOBILITY PTE. LTD.,Combo 2,50,DC,0.8938,kWh,R114858R-002,1
4,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,142A PASIR RIS STREET 11 SINGAPORE 511142,511142,103.959758,1.362839,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,L3A 129,1,STRIDES YTL PTE. LTD.,Type 2,7.4,AC,0.6980,kWh,R122902D-001,1

There are only 3 types of data from above table:
- string
- integer
- float

Since all the columns are already in object and string is consider as an object, we will only convert the rest to the 2 data type in one go by data type:

In [38]:
ev_integer_col= ['postal_code','plug_status','evcp_status']
ev_float_col= ['longtitude','latitude','power_rating', 'price' ]

for items in ev_integer_col:
    ev_df_final[items]=pd.to_numeric(ev_df_final[items],downcast='integer', errors='coerce') # errors='coerce' - turn invalid values into NaN

for items in ev_float_col:
    ev_df_final[items]=pd.to_numeric(ev_df_final[items],downcast='float',errors='coerce')# errors='coerce' - turn invalid values into NaN

Double check if changes are updated as follows:

In [39]:
ev_df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11310 entries, 0 to 11309
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   point_location  10846 non-null  object
 1   point_address   11310 non-null  object
 2   postal_code     11310 non-null  int32
 3   longtitude      11310 non-null  float32
 4   latitude        11310 non-null  float32
 5   plug_location   10865 non-null  object
 6   plug_position   11310 non-null  object
 7   plug_status     11310 non-null  int8
 8   plug_operator   11310 non-null  object
 9   plug_type       11310 non-null  object
 10  power_rating    11310 non-null  float32
 11  current         11310 non-null  object
 12  price           11093 non-null  float32
 13  price_unit      11055 non-null  object
 14  evcp_id         11310 non-null  object
 15  evcp_status     11097 non-null  float64
dtypes: float32(4), float64(1), int32(1), int8(1), object(9)
memory usage: 1.1+ MB

### [ LOAD ]

#### Establish connection

In [40]:
import sqlalchemy as db
from sqlalchemy_utils import create_database, database_exists
from sqlalchemy import text

<mark> Please enter your details to continue

In [121]:
USERNAME = 'postgres'
PASSWORD = ''# enter your password 
HOST     = ''# enter the host
PORT     = ''# enter port
DB_NAME  = 'ev_charging_points' #enter your database name

CONNECTION_STRING = f'postgresql://{USERNAME}:{PASSWORD}@{HOST}:{PORT}/{DB_NAME}'
print(f"Connection string: postgresql://{USERNAME}:****@{HOST}:{PORT}/{DB_NAME}")

engine = db.create_engine(CONNECTION_STRING)

if not database_exists(engine.url):
    create_database(engine.url)
    print(f"✅ Database '{DB_NAME}' created successfully!")
else:
    print(f"ℹ️  Database '{DB_NAME}' already exists — skipping creation.")

Connection string: postgresql://postgres:****@localhost:5432/ev_charging_points
✅ Database 'ev_charging_points' created successfully!

#### Importing from Python to SQL

In [122]:
ev_df_final.to_sql("ev_charging_points", engine, index=False, if_exists='fail')

310

##### <u> Check if database has received all entries

In [123]:
ev_db = pd.read_sql('SELECT * FROM ev_charging_points', engine)
print(f"Rows retrieved: {len(ev_db)}")
ev_db.head()

Rows retrieved: 11310

,point_location,point_address,postal_code,longtitude,latitude,plug_location,plug_position,plug_status,plug_operator,plug_type,power_rating,current,price,price_unit,evcp_id,evcp_status
0,CLARKE QUAY,3E RIVER VALLEY ROAD SINGAPORE 179024,179024,103.846725,1.290314,CLARKE QUAY,L4 49,1,SP MOBILITY PTE. LTD.,Type 2,22.0,AC,0.8066,kWh,R114859D-001,1.0
1,CLARKE QUAY,3E RIVER VALLEY ROAD SINGAPORE 179024,179024,103.846725,1.290314,CLARKE QUAY,L4 50,0,SP MOBILITY PTE. LTD.,Type 2,22.0,AC,0.8066,kWh,R114861R-001,0.0
2,CLARKE QUAY,3E RIVER VALLEY ROAD SINGAPORE 179024,179024,103.846725,1.290314,CLARKE QUAY,L4 51 & 52,1,SP MOBILITY PTE. LTD.,Combo 2,50.0,DC,0.8938,kWh,R114858R-001,1.0
3,CLARKE QUAY,3E RIVER VALLEY ROAD SINGAPORE 179024,179024,103.846725,1.290314,CLARKE QUAY,L4 51 & 52,1,SP MOBILITY PTE. LTD.,Combo 2,50.0,DC,0.8938,kWh,R114858R-002,1.0
4,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,142A PASIR RIS STREET 11 SINGAPORE 511142,511142,103.959755,1.362839,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,L3A 129,1,STRIDES YTL PTE. LTD.,Type 2,7.4,AC,0.6980,kWh,R122902D-001,1.0

All columns successfuly imported.

In [124]:
ev_db_info_schema = pd.read_sql(
    '''SELECT column_name,
            data_type
    FROM information_schema.columns
    WHERE table_name = 'ev_charging_points' 
    ORDER BY ordinal_position ''', engine)
print(ev_db_info_schema)

       column_name         data_type
0   point_location              text
1    point_address              text
2      postal_code           integer
3       longtitude              real
4         latitude              real
5    plug_location              text
6    plug_position              text
7      plug_status          smallint
8    plug_operator              text
9        plug_type              text
10    power_rating              real
11         current              text
12           price              real
13      price_unit              text
14         evcp_id              text
15     evcp_status  double precision

##### <u> Making changes to evcp_status with SQL

Unable to convert evcp_status on python. Inspect the unique data for evcp_status first.

In [125]:
evcp_status_data_type = pd.read_sql(
    '''SELECT distinct evcp_status, count(*) 
       FROM ev_charging_points 
       GROUP BY evcp_status ''', engine)
print(evcp_status_data_type)

   evcp_status  count
0          0.0   1859
1          1.0   9256
2          NaN    195

Looking fine with no concern, proceed with converting to integer, making changes on sql database with python

In [126]:
command =(
    '''ALTER TABLE ev_charging_points
       ALTER COLUMN evcp_status 
       TYPE integer;''')

with engine.begin() as conn:
    conn.execute(text(command))

Check if change has been updated

In [127]:
ev_db_info_schema_updated = pd.read_sql(
    '''SELECT column_name,
            data_type
    FROM information_schema.columns
    WHERE table_name = 'ev_charging_points' 
    ORDER BY ordinal_position ''', engine)
display(pd.DataFrame(ev_db_info_schema_updated))

       column_name data_type
0   point_location      text
1    point_address      text
2      postal_code   integer
3       longtitude      real
4         latitude      real
5    plug_location      text
6    plug_position      text
7      plug_status  smallint
8    plug_operator      text
9        plug_type      text
10    power_rating      real
11         current      text
12           price      real
13      price_unit      text
14         evcp_id      text
15     evcp_status   integer

### [DATABASE DESIGN]

<mark>to insert image of the ERD>

Explain why it is designed to be this way

#### Creation of empty tables &
#### Migrating of columns from original table to new tables

##### <u> Any subpoint here underline

In [128]:
# convert data type to varchar(6) for postal code and add 0 to all 5 digit postal code

commands =(
    '''ALTER TABLE ev_charging_points
       ALTER COLUMN postal_code TYPE VARCHAR(6);''',

    '''UPDATE ev_charging_points
       SET postal_code = CONCAT('0', postal_code)
       WHERE LENGTH(postal_code) < 6;''',
       )

for command in commands:
    with engine.begin() as conn:
        conn.execute(text(command))

In [129]:
# checking change is updated

postal_code_check = pd.read_sql(text(
    """SELECT postal_code
       FROM ev_charging_points 
       WHERE postal_code LIKE '0%'; """), engine)

print(postal_code_check.head())

  postal_code
0      050004
1      080108
2      049712
3      068897
4      048423

In [130]:
# create table for dim_location and set postal code as PRIMARY KEY

command =(
    '''DROP TABLE IF EXISTS dim_location;
        CREATE TABLE dim_location (
    	postal_code VARCHAR(6) PRIMARY KEY,
    	point_location TEXT,
        point_address  TEXT,
        longtitude     REAL,
        latitude       REAL);

        INSERT INTO dim_location
        SELECT DISTINCT postal_code, point_location, point_address, longtitude, latitude
        FROM ev_charging_points;''')

with engine.begin() as conn:
    conn.execute(text(command))

In [131]:
# checking table dim_location

pd.read_sql(
    '''SELECT *
       FROM dim_location 
       LIMIT 10;''', engine)

,postal_code,point_location,point_address,longtitude,latitude
0,651628,BLK 628A BUKIT BATOK CENTRAL MULTI STOREY CAR ...,628A BUKIT BATOK CENTRAL SINGAPORE 651628,103.749886,1.350867
1,369683,HARPER POINT,25 HARPER ROAD SINGAPORE 369683,103.887110,1.334315
2,360207,BLK 207 WOODLEIGH LINK WOODLEIGH GLEN,207 WOODLEIGH LINK SINGAPORE 360207,103.871475,1.341762
3,169662,KING'S CENTRE,390 HAVELOCK ROAD SINGAPORE 169662,103.835686,1.289631
4,640273,BLK 273 JURONG WEST AVENUE 3 MULTI STOREY CAR ...,273 JURONG WEST AVENUE 3 SINGAPORE 640273,103.702820,1.351974
5,681567,BLK 567A CHOA CHU KANG STREET 52 MULTI STOREY ...,567A CHOA CHU KANG STREET 52 SINGAPORE 681567,103.746150,1.395381
6,511158,BLK 158A PASIR RIS STREET 13 MULTI STOREY CAR ...,158A PASIR RIS STREET 13 SINGAPORE 511158,103.961680,1.364160
7,750505,MONTREAL SPRING,505 CANBERRA LINK SINGAPORE 750505,103.822530,1.450262
8,319457,STORHUB TOA PAYOH,743 LORONG 5 TOA PAYOH SINGAPORE 319457,103.852370,1.333120
9,732891,MULTI STOREY CAR PARK,891C WOODLANDS DRIVE 50 SINGAPORE 732891,103.791450,1.438186

In [132]:
# create table for dim_charger and set charger_id as PRIMARY KEY

command =(
    '''DROP TABLE IF EXISTS dim_charger;
        CREATE TABLE dim_charger (
    	charger_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    	plug_type  TEXT,
        current    TEXT,
        price_unit TEXT);

        INSERT INTO dim_charger (plug_type, current, price_unit)
        SELECT DISTINCT plug_type, current, price_unit
        FROM ev_charging_points
        GROUP BY plug_type, current, price_unit;''')

with engine.begin() as conn:
    conn.execute(text(command))

In [133]:
# checking table dim_charger

pd.read_sql(
    '''SELECT *
       FROM dim_charger 
       LIMIT 10;''', engine)

   charger_id plug_type current price_unit
0           1   CHAdeMO      DC        kWh
1           2   CHAdeMO      DC       None
2           3   Combo 2      DC       free
3           4   Combo 2      DC          h
4           5   Combo 2      DC        kWh
5           6   Combo 2      DC       None
6           7    Type 2      AC          h
7           8    Type 2      AC        kWh
8           9    Type 2      AC       None

In [134]:
# create table for dim_plug_operator and set plug_operator_id as PRIMARY KEY

command =(
    '''DROP TABLE IF EXISTS dim_plug_operator;
        CREATE TABLE dim_plug_operator (
    	plug_operator_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    	plug_operator  TEXT);

        INSERT INTO dim_plug_operator (plug_operator)
        SELECT DISTINCT plug_operator
        FROM ev_charging_points''')

with engine.begin() as conn:
    conn.execute(text(command))

In [135]:
# checking table dim_plug_operator

pd.read_sql(
    '''SELECT *
       FROM dim_plug_operator 
       LIMIT 10;''', engine)

   plug_operator_id                    plug_operator
0                 1                G. TECH PTE. LTD.
1                 2           UP SOLUTIONS PTE. LTD.
2                 3       WES CARES ENERGY PTE. LTD.
3                 4           EIGEN ENERGY PTE. LTD.
4                 5  P-Parking International Pte Ltd
5                 6          ALPINA ENERGY PTE. LTD.
6                 7            STRIDES YTL PTE. LTD.
7                 8                AIRETEC PTE. LTD.
8                 9               ENEREADY PTE. LTD.
9                10            EV MOBILITY PTE. LTD.

In [136]:
# create table for dim_evcp_status and tag occupied, available, not available
# set evcp_status as PRIMARY KEY

commands =(
     '''UPDATE ev_charging_points
        SET evcp_status = 2
        WHERE evcp_status IS NULL;''',
    
     '''DROP TABLE IF EXISTS dim_evcp_status;
        CREATE TABLE dim_evcp_status (
    	evcp_status INTEGER PRIMARY KEY,
    	status      TEXT);''',

    '''INSERT INTO dim_evcp_status
        SELECT DISTINCT evcp_status
        FROM ev_charging_points;''',
    
    '''UPDATE dim_evcp_status
        SET status = 'OCCUPIED'
        WHERE evcp_status = 0;''',

    '''UPDATE dim_evcp_status
        SET status = 'AVAILABLE'
        WHERE evcp_status = 1;''',

    '''UPDATE dim_evcp_status
        SET status = 'NOT AVAILABLE'
        WHERE evcp_status = 2;''')

for command in commands:
    with engine.begin() as conn:
        conn.execute(text(command))

In [137]:
# checking table dim_evcp_status

pd.read_sql(
    '''SELECT *
       FROM dim_evcp_status 
       LIMIT 10;''', engine)

   evcp_status         status
0            0       OCCUPIED
1            1      AVAILABLE
2            2  NOT AVAILABLE

In [138]:
# create table for fact_ev_charging_points and setting foreign keys

command =(
     '''DROP TABLE IF EXISTS fact_ev_charging_points;
        CREATE TABLE fact_ev_charging_points (
    	evcp_id TEXT     PRIMARY KEY,
        postal_code      VARCHAR(6) REFERENCES dim_location (postal_code),
        plug_operator_id INTEGER REFERENCES dim_plug_operator (plug_operator_id),
        charger_id       INTEGER REFERENCES dim_charger (charger_id),
    	plug_position    TEXT,
        evcp_status      INTEGER REFERENCES dim_evcp_status (evcp_status),
        power_rating     REAL,
        price            REAL);

        INSERT INTO fact_ev_charging_points
        SELECT ev_charging_points.evcp_id, 
                ev_charging_points.postal_code,
                dim_plug_operator.plug_operator_id,
                dim_charger.charger_id,
                ev_charging_points.plug_position,
                ev_charging_points.evcp_status,
                ev_charging_points.power_rating,
                ev_charging_points.price
        FROM ev_charging_points
        LEFT JOIN dim_plug_operator ON ev_charging_points.plug_operator = dim_plug_operator.plug_operator
        LEFT JOIN dim_charger ON ev_charging_points.plug_type = dim_charger.plug_type
                                    AND ev_charging_points.current = dim_charger.current
                                    AND ev_charging_points.price_unit = dim_charger.price_unit;''')

with engine.begin() as conn:
    conn.execute(text(command))

In [139]:
# checking table fact_ev_charging_points

pd.read_sql(
    '''SELECT *
       FROM fact_ev_charging_points 
       LIMIT 10;''', engine)

,evcp_id,postal_code,plug_operator_id,charger_id,plug_position,evcp_status,power_rating,price
0,R108244C-001,648166,8,8,L1 285,0,22.0,0.45
1,R108250D-001,648166,8,8,L1 287,1,22.0,0.45
2,R108246R-001,648166,8,8,L1 286,0,22.0,0.45
3,R115044C-001,737853,8,8,L6 32,0,22.0,0.45
4,R115038B-001,159971,8,8,L4 45,1,22.0,0.50
5,R115043Z-001,737853,8,8,L6 30,0,22.0,0.45
6,R115035A-001,068906,8,8,B3 7,1,22.0,0.60
7,R106883R-001,629853,8,8,L1 38,0,22.0,0.50
8,R115045G-001,737853,8,8,L6 31,2,22.0,0.45
9,R106872A-001,629853,8,8,L1 37,0,22.0,0.50

In [140]:
# checking constraints primary and foreign keys

pd.read_sql(text(
    '''SELECT constraint_name, table_name, constraint_type
        FROM information_schema.table_constraints
        WHERE table_name NOT LIKE 'pg%';'''), engine)

,constraint_name,table_name,constraint_type
0,dim_location_postal_code_not_null,dim_location,CHECK
1,dim_location_pkey,dim_location,PRIMARY KEY
2,dim_charger_charger_id_not_null,dim_charger,CHECK
3,dim_charger_pkey,dim_charger,PRIMARY KEY
4,dim_plug_operator_plug_operator_id_not_null,dim_plug_operator,CHECK
5,dim_plug_operator_pkey,dim_plug_operator,PRIMARY KEY
6,dim_evcp_status_evcp_status_not_null,dim_evcp_status,CHECK
7,dim_evcp_status_pkey,dim_evcp_status,PRIMARY KEY
8,fact_ev_charging_points_evcp_id_not_null,fact_ev_charging_points,CHECK
9,fact_ev_charging_points_pkey,fact_ev_charging_points,PRIMARY KEY
10,fact_ev_charging_points_postal_code_fkey,fact_ev_charging_points,FOREIGN KEY
11,fact_ev_charging_points_plug_operator_id_fkey,fact_ev_charging_points,FOREIGN KEY
12,fact_ev_charging_points_charger_id_fkey,fact_ev_charging_points,FOREIGN KEY
13,fact_ev_charging_points_evcp_status_fkey,fact_ev_charging_points,FOREIGN KEY

### [ANALYZE]